Repository KhronosGroup/Vulkan-LoaderAndValidationLayers, pull requests merged in 2018-02, with the labels that each got.

#2394 layers: fix unexpected errors in layer tests
  layers/parameter_validation_utils.cpp
  layers/vk_validation_error_database.txt
  tests/layer_validation_tests.cpp
Labels: bug

#2405 loader: Don't add duplicate JSON files from Khronos registry path.
  loader/loader.c
Labels: loader

#2411 tests: Add test to verify issue 2213 fixed
  tests/layer_validation_tests.cpp
Labels: bug

#2420 Update to version 1.0.69 of the Vulkan hdr
  icd/linux/VkICD_mock_icd.json
  icd/windows/VkICD_mock_icd.json
  include/vulkan/vulkan.h
  include/vulkan/vulkan.hpp
  layers/linux/VkLayer_core_validation.json
  layers/linux/VkLayer_object_tracker.json
  layers/linux/VkLayer_parameter_validation.json
  layers/linux/VkLayer_standard_validation.json
  layers/linux/VkLayer_threading.json
  layers/linux/VkLayer_unique_objects.json
  layers/vk_validation_error_database.txt
  layers/vk_validation_error_messages.h
  layers/windows/VkLayer_core_validation.json
  layers/windows/VkLayer_object_tracker.json
  layers/windows/VkLayer_parameter_validation.json
  layers/windows/VkLayer_standard_validation.json
  layers/windows/VkLayer_threading.json
  layers/windows/VkLayer_unique_objects.json
  scripts/vk.xml
  scripts/vuid_mapping.py
  tests/layers/linux/VkLayer_device_profile_api.json
  tests/layers/linux/VkLayer_test.json
  tests/layers/linux/VkLayer_wrap_objects.json
  tests/layers/windows/VkLayer_device_profile_api.json
  tests/layers/windows/VkLayer_test.json
  tests/layers/windows/VkLayer_wrap_objects.json
Labels: enhancement

#2435 Modify .gitattributes for unix line endings on shell scripts
  .gitattributes
Labels: bug

#2430 Fix line endings in update_external_resources shell script
  update_external_sources.sh
Labels: enhancement

#2439 Kill old vuids -- buffer image transfer granularity checks & image layer range checks
  layers/buffer_validation.cpp
  layers/vk_validation_error_database.txt
  tests/layer_validation_tests.cpp
Labels: bug

#2425 Reorganize and update BUILD.md
  BUILD.md
Labels: enhancement

#2445 tests: Clean cmath and climits usage
  tests/layer_validation_tests.cpp
Labels: enhancement
